mode: 0 #mode=0 本机模式，启动后会根据rate设置的时间运行 mode=1 github_action模式，每次启动只运行一次
station_id:  #站点id 通过抓包得到，也可以不填写此字段，只填写下面的经纬度，填写此字段后经纬度的配置不会生效
# rate在GitHub模式下不生效 需要在GitHub action配置文件配置
rate: 10 # 监控频率，单位：秒
stock_monitor: true #库存检测开关 根据关键词和价格检测
# 当有含有某关键词的商品有库存且此商品价格小于等于设置价格，同时当前有运力的时候就会提醒
# 若未设置关键词，默认任意商品拥有库存均会提醒
#注意 开启库存检测后 无库存有运力的情况下不会提醒
keywords:
  - name: 馒头
    price: 15 #小于或等于此价格的才会提醒 相当于价格设置为零或者不填，则默认不限制价格
  - name: 桃太郎粉番茄
    price: 0
#地理位置信息 填写经纬度之后则不需要填写，站点id，经纬度可以通过https://lbs.amap.com/tools/picker 获取
latitude: 31.223505
longitude: 121.44532
bark:
  id: #bark id 支持多设备
    -
    -
  sound: alarm #通知声音
